version: "3.8"
services:
  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: Brothers1102319
      POSTGRES_DB: Brothers
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d Brothers"]

      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"

  express:
    build:
      context: ./express
    container_name: express
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy

    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"

volumes:
  postgres-data:
